import React, { useState } from "react";

const Assessment = () => {
  const subjects = [
      "English", "Math", "Science", "Social", "Computing", "Career Tech", "Creative Art",
          "French", "RME", "Ga", "History", "OWOP"
            ];

              const classes = Array.from({ length: 9 }, (_, i) => `Class ${i + 1}`).concat([
                  "JHS 1", "JHS 2", "JHS 3"
                    ]);

                      const sheetLinks = {
                          "Computing_JHS 1": "https://docs.google.com/spreadsheets/d/1oJU0E8cdQIVdPePm2BJAWLyTeJuoXDy65SQQx8d9z9A/edit?usp=drivesdk",
                              // Add more subject_class combinations with their Google Sheets links
                                };

                                  const [selectedClass, setSelectedClass] = useState("");
                                    const [selectedSubject, setSelectedSubject] = useState("");

                                      const key = `${selectedSubject}_${selectedClass}`;
                                        const selectedLink = sheetLinks[key];

                                          return (
                                              <div style={styles.container}>
                                                    <h1 style={styles.title}>School Subject Sheet Viewer</h1>

                                                          <div style={styles.selectGroup}>
                                                                  <select
                                                                            value={selectedClass}
                                                                                      onChange={(e) => {
                                                                                                  setSelectedClass(e.target.value);
                                                                                                              setSelectedSubject("");
                                                                                                                        }}
                                                                                                                                  style={styles.select}
                                                                                                                                          >
                                                                                                                                                    <option value="">-- Choose Class --</option>
                                                                                                                                                              {classes.map((cls) => (
                                                                                                                                                                          <option key={cls} value={cls}>
                                                                                                                                                                                        {cls}
                                                                                                                                                                                                    </option>
                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                      </select>

                                                                                                                                                                                                                              <select
                                                                                                                                                                                                                                        value={selectedSubject}
                                                                                                                                                                                                                                                  onChange={(e) => setSelectedSubject(e.target.value)}
                                                                                                                                                                                                                                                            style={styles.select}
                                                                                                                                                                                                                                                                      disabled={!selectedClass}
                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                        <option value="">-- Choose Subject --</option>
                                                                                                                                                                                                                                                                                                  {subjects.map((subject) => (
                                                                                                                                                                                                                                                                                                              <option key={subject} value={subject}>
                                                                                                                                                                                                                                                                                                                            {subject}
                                                                                                                                                                                                                                                                                                                                        </option>
                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                      {selectedLink ? (
                                                                                                                                                                                                                                                                                                                                                                              <iframe
                                                                                                                                                                                                                                                                                                                                                                                        src={selectedLink}
                                                                                                                                                                                                                                                                                                                                                                                                  title="Google Sheet Viewer"
                                                                                                                                                                                                                                                                                                                                                                                                            style={styles.iframe}
                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                  selectedClass &&
                                                                                                                                                                                                                                                                                                                                                                                                                                          selectedSubject && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <p style={styles.errorMessage}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                No sheet link available for {selectedSubject} – {selectedClass}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const styles = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                container: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontFamily: "Segoe UI, sans-serif",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: "#f1f5f9",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            minHeight: "100vh",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "40px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxWidth: "800px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        margin: "0 auto",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            title: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontSize: "2rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#1e293b",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            marginBottom: "40px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                selectGroup: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        flexDirection: "column",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gap: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                marginBottom: "30px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    select: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        padding: "10px 14px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            border: "1px solid #cbd5e1",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontSize: "1rem",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        outline: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            iframe: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    height: "80vh",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "8px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: "0 2px 12px rgba(0, 0, 0, 0.08)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    errorMessage: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#dc2626",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            textAlign: "center",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fontWeight: 500,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    marginTop: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      export default Assessment;