import React, { useState } from "react";
import Breadcrumb from "../breadcrumb";
import Header from "../header";

const Assessment = () => {
  const [selectedClass, setSelectedClass] = useState("");
    const [selectedSubject, setSelectedSubject] = useState("");
      const [sheetUrl, setSheetUrl] = useState("");

        const classes = [
            "Class 1", "Class 2", "Class 3",
                "Class 4", "Class 5", "Class 6",
                    "JHS 1", "JHS 2", "JHS 3"
                      ];

                        const subjects = [
                            "Ga", "Computing", "Creative Art", "Math", "Science",
                                "History", "Owop", "French", "Social", "English","Health Safety",
                                    "Career Tech", "RME", "Library"
                                      ];

                                        // Link store — you can add more
                                          const sheetLinks = {
                                              "Computing_JHS 1": "https://docs.google.com/spreadsheets/d/1oJU0E8cdQIVdPePm2BJAWLyTeJuoXDy65SQQx8d9z9A/edit",
                                              "Ga_JHS 1":"https://docs.google.com/spreadsheets/d/1-p_JRZlXBLAWs4B70qIvUxAw-C4cM3jC/edit", 
                                              "Creative Art_JHS 1":"https://docs.google.com/spreadsheets/d/1005Rf3xYGEx28p-CzJ0Dfb-FAF3fQKHP/edit",
                                              "Math_JHS 1":"https://docs.google.com/spreadsheets/d/1-mddl0uG_AM90nsxZmpJFPOA5J-dYIVC/edit",
                                              "Science_JHS 1":"https://docs.google.com/spreadsheets/d/1-fFv1PxRkVcbQJ9pm7k_6rIILGWrvorv/edit",
                                              "French_JHS 1":"https://docs.google.com/spreadsheets/d/1-wvb72Jkd5jFP1CuRbzLcC9ZNCukHZ_6/edit", 
                                              "Social_JHS 1":"https://docs.google.com/spreadsheets/d/1-h67MKcYsdDmh-VTtb8Y3apTv1RqJ-1k/edit", 
                                              "English_JHS 1":"https://docs.google.com/spreadsheets/d/1-uYj3akmfj4Oa1l-Z2ASqUAXD3-9XTzS/edit",
                                              "Career Tech_JHS 1":"https://docs.google.com/spreadsheets/d/1-TB2YBgFYJ1q7Jwk11MyPBXsZ-x1VAen/edit",
                                              "RME_JHS 1":"https://docs.google.com/spreadsheets/d/1-mMzUJAcOEooXSz_MupwtEM98toVdGfw/edit",
                                              "Ga_JHS 2":"https://docs.google.com/spreadsheets/d/10evZxOEUq_gzNc2ae-o42GVgiIdA0VeX/edit", 
                                              "Creative Art_JHS 2":"https://docs.google.com/spreadsheets/d/10k0zLjYdettjunLMVOk3jszE8lKs1aVW/edit",
                                              "Math_JHS 2":"https://docs.google.com/spreadsheets/d/10VSfIeG1aOXxb60KRxJ6XaK8boM41dTs/edit",
                                              "Science_JHS 2":"https://docs.google.com/spreadsheets/d/10OodmNFrvB-8VOtK_VqPY6nQqkZxgVhB/edit",
                                              "French_JHS 2":"https://docs.google.com/spreadsheets/d/10iP7NdZ2SpQY8Yvo-K97SQl9tibFYgKe/edit", 
                                              "Social_JHS 2":"https://docs.google.com/spreadsheets/d/10Jamt35axQ6KRroyEAQHMNzOlWPl6QSe/edit", 
                                              "English_JHS 2":"https://docs.google.com/spreadsheets/d/10fazLxwDwcRNkbz2Sls5am_gnqXVej8s/edit",
                                              "Career Tech_JHS 2":"https://docs.google.com/spreadsheets/d/10qNBh0Cs6YwWwVXjMCZlxW_nqoNCwppc/edit",
                                              "RME_JHS 2":"https://docs.google.com/spreadsheets/d/10USoJVkcShrVO9r7WGlrYgAaukI3EV3N/edit",
                                              "Computing_JHS 2":"https://docs.google.com/spreadsheets/d/10bVhcUdA25jvpRGxrB7zZMvZwIWSOLwf/edit",
                                              "Ga_Class 6":"https://docs.google.com/spreadsheets/d/14bt2cIKD4gWmT-IDuhGPLuHVyGUvkjUb/edit",
                                              "Owop_Class 6":"https://docs.google.com/spreadsheets/d/14yNdfgsRlLKC7RDJnxrkbwLkQA9kcVEm/edit",
                                              "RME_Class 6":"https://docs.google.com/spreadsheets/d/14vMIlkGGAffulTIeAh0QlGMRg_PFBHI_/edit",
                                              "Career tech_Class 6":"https://docs.google.com/spreadsheets/d/14SHy4wu_xpFuOg1ZJWgMCogPhajiXQHt/edit",
                                              "French_Class 6":"https://docs.google.com/spreadsheets/d/14fpiwyWzRU-LoLWFUXnuox07GhyNk6zz/edit",
                                              "Computing_Class 6":"https://docs.google.com/spreadsheets/d/15-fPA75lq3P4YKc3xCu_1VAFIRM_CYBr/edit",
                                              "Creative Art_Class 6":"https://docs.google.com/spreadsheets/d/14m3kFA5lX4dUDqL9GQEZlFE7zl6BvK_q/edit",
                                              "History_Class 6":"https://docs.google.com/spreadsheets/d/14YXDcPhZdtiMQ3Hyq5A5Ey5wqxe7lYxk/edit",
                                              "Science_Class 6":"https://docs.google.com/spreadsheets/d/14v1wWYSf0z4jKza1pMzeybKmQoGxXlfz/edit",
                                              "Math_Class 6":"https://docs.google.com/spreadsheets/d/151g8cpQsDxPLiet2WOouFY6jLM-anIOa/edit",
                                              "English_Class 6":"https://docs.google.com/spreadsheets/d/14iGUiXaXZIm-UOkcGt-QCBiOeicW4xuF/edit",
                                              "Ga_Class 5":"https://docs.google.com/spreadsheets/d/14Q1DRTEiB1-fEESk3ZD7Ub916mYw-zgV/edit",
                                              "Owop_Class 5":"https://docs.google.com/spreadsheets/d/14DVUY0s4KGFwNjoTCeKu32j88olG7Y6f/edit",
                                              "RME_Class 5":"https://docs.google.com/spreadsheets/d/148mA37NkPnbD4yo3Awfw8wJXafwstbvB/edit",
                                              "Career tech_Class 5":"https://docs.google.com/spreadsheets/d/147FMMEBkbTasuDvRaZs7ap6aZaUzZZG-/edit",
                                              "French_Class 5":"https://docs.google.com/spreadsheets/d/14-u17dVI4HD32nDLD5cldUQ2dKDpAMa2/edit",
                                              "Computing_Class 5":"https://docs.google.com/spreadsheets/d/14EXFHUxDN7ubjEepOxQQOTzrchtQeg6b/edit",
                                              "Creative Art_Class 5":"https://docs.google.com/spreadsheets/d/143XNTRnXcDt0g-bj728aHmN5WYL70E4m/edit",
                                              "History_Class 5":"https://docs.google.com/spreadsheets/d/14P0-H4YQ1iBLfT7dzSIMz6Zz7N1jsIRw/edit",
                                              "Science_Class 5":"https://docs.google.com/spreadsheets/d/148BDAutbdK_gIo2v7pz2xcHrzhtjGEMC/edit",
                                              "Math_Class 5:":"https://docs.google.com/spreadsheets/d/14GvyQCbrPUn5b-YSG8Iyy21GduLVW9tc/edit",
                                              "English_Class 5":"https://docs.google.com/spreadsheets/d/143KQDAmNhOBY_YsXTgYco4NNcD64AtxB/edit",
                                              "Ga_Class 4":"https://docs.google.com/spreadsheets/d/13a3BcM-1_JfRX2_7R3U7djgIRl8wy9ai/edit",
                                              "Owop_Class 4":"https://docs.google.com/spreadsheets/d/13xbu2Fn2fFcvwuB0j5QCPHFrS3LXTTf1/edit",
                                              "RME_Class 4":"https://docs.google.com/spreadsheets/d/13vtXGPRdq-mNQoMzQACiHpV2RJqA0f8q/edit",
                                              "Career tech_Class 4":"https://docs.google.com/spreadsheets/d/13JuZBA0umLlv16L0lrLUC8AP4MSb4dXM/edit",
                                              "French_Class 4":"https://docs.google.com/spreadsheets/d/13hMOmTpuk3oh1Z3TEN6eenA9SwzAbX4C/edit",
                                              "Computing_Class 4":"https://docs.google.com/spreadsheets/d/13z516MavGtE0nUqmWB81UhAmB1izvQN8/edit",
                                              "Creative Art_Class 4":"https://docs.google.com/spreadsheets/d/13lleDGTtsk7Fky1_pz-RiFaT20VYSaaq/edit",
                                              "History_Class 4":"https://docs.google.com/spreadsheets/d/13RWGM8Ke94gEolWsMUVSPRHwz7-iASl_/edit",
                                              "Science_Class 4":"https://docs.google.com/spreadsheets/d/13MdJu9JaPOSuyfPmYk4Qg0-krcDYO6TS/edit",
                                              "Math_Class 4":"https://docs.google.com/spreadsheets/d/13MdJu9JaPOSuyfPmYk4Qg0-krcDYO6TS/edit",
                                              "English_Class 4":"https://docs.google.com/spreadsheets/d/13jnGr5PtxhBUZQgDSAmGbYtszUqWj6ja/edit",
                                              "Health Safety_Class 4":"https://docs.google.com/spreadsheets/d/13So6KPrN_Q_eeuu_Styr5tnwdVj41Zop/edit",
                                              "Ga_Class 1":"https://docs.google.com/spreadsheets/d/11E6yv_jlWAUdhLBm1FeIrFnEth_Xjg5c/edit",
                                              "RME_Class 1":"https://docs.google.com/spreadsheets/d/1105ZtK6n8yoco_oX50_k6OAH4bNU-IAV/edit",
                                              "Health Safety_Class 1":"https://docs.google.com/spreadsheets/d/115ft5oAQ1_aLpOZGRvpQDrS01i9Y7cwA/edit",
                                              "French_Class 1":"https://docs.google.com/spreadsheets/d/11FoCOe5Uc1fZkgXUMWWcWfMvo_9-QBzg/edit",
                                              "Computing_Class 1":"https://docs.google.com/spreadsheets/d/112zmRbljo1idacddfAU6Pchn64OYTcx-/edit",
                                              "History_Class 1":"https://docs.google.com/spreadsheets/d/115G6qfPIY-o8sFFlO3pRraw3IZFNtDKx/edit",
                                              "Science_Class 1":"https://docs.google.com/spreadsheets/d/10yhblO2sV7PCwtmufCU0nrtBDZC_23cl/edit",
                                              "Math_Class 1":"https://docs.google.com/spreadsheets/d/11336xtuYI53d5x9PLSS71jJgb7iBKXLe/edit",
                                              "English_Class 1":"https://docs.google.com/spreadsheets/d/11HmSXNp8_P3LcUdzRa7OrCWphHCxeRlD/edit",
                                              "Ga_Class 2": "https://docs.google.com/spreadsheets/d/12AcQh4mpqTHM4oqm5UpkFMmmIzq-IInW/edit",
                                              "RME_Class 2":"https://docs.google.com/spreadsheets/d/11aqCkzldUtGRJ5TwJfcFlyeP-iCzVogj/edit",
                                              "French_Class 2":"https://docs.google.com/spreadsheets/d/12GjiBGLOQLi8KStFJ009wq6LvEob3R7x/edit",
                                              "Computing_Class 2":"https://docs.google.com/spreadsheets/d/11kKA1FdtE_AnpuM3a8UyuGqtpfQeC5eE/edit",
                                              "Creative Art_Class 2":"https://docs.google.com/spreadsheets/d/12NA7dIxNvh6nK7WTQ_8wOu8MR9ZoZEtt/edit",
                                              "History_Class 2":"https://docs.google.com/spreadsheets/d/11ySnnQvVCjnaCguP1zB8EuDSfE1RkVPS/edit",
                                              "Science_Class 2":"https://docs.google.com/spreadsheets/d/11THjk4LRBnqdyTxRxrtazV2H3d8S8rOn/edit",
                                              "Math_Class 2":"https://docs.google.com/spreadsheets/d/11no_ziIg-y0c4H1LUMXjHeLrEicMrgD4/edit",
                                              "English_Class 2":"https://docs.google.com/spreadsheets/d/12MoP8aHpaWBLu__QqtzJXpElrQ3jaPTM/edit",
                                              "Health Safety_Class 2":"https://docs.google.com/spreadsheets/d/128WsyccgAy5-q9Lu8Wlz7-A8WOAz-6th/edit",

                                              "Ga_Class 3":"https://docs.google.com/spreadsheets/d/12cok-i6NFIT1FOvBfh_hPwlXV5YviZdu/edit",
                                              "Owop_Class 3":"https://docs.google.com/spreadsheets/d/12nDt3QFToDhqMm6axqElA8lTFLAvc2do/edit",
                                              "RME_Class 3":"https://docs.google.com/spreadsheets/d/12ifJxs2SUy5aOnX_3ueuaO3SPrEEoLQR/edit",
                                              "Health Safety_Class 3":"https://docs.google.com/spreadsheets/d/12b0fTNeOoJ_zaAxTut8XNO0lFI6u5cLR/edit",
                                              "French_Class 3":"https://docs.google.com/spreadsheets/d/12eEJz0YiRbTI0rc-N0XmFyIhow7_dxWw/edit",
                                              "Computing_Class 3":"https://docs.google.com/spreadsheets/d/12ohmZP4qw8OthDXOBQFSJUDJFIe5obj1/edit",
                                              "Creative Art_Class 3":"https://docs.google.com/spreadsheets/d/12Ns1lDQ8QHZgUOQlz4jTI4HiMzVfvJNc/edit",
                                              "History_Class 3":"https://docs.google.com/spreadsheets/d/12udQ86xhjM0QlLKwlCiAUgnKRuz_A42u/edit",
                                              "Science_Class 3":"https://docs.google.com/spreadsheets/d/12gUqD473nAkdauQMqBtB8Y6PxyECUAdb/edit",
                                              "Math_Class 3":"https://docs.google.com/spreadsheets/d/12pG0i-qhkRipTrn2eqLgu5JI1_vyHmP_/edit",
                                              "English_Class 3":"https://docs.google.com/spreadsheets/d/12eYNZnSNwN0m9vcmh89stv0lfKg1NLlx/edit"
                                                };

                                                  const handleLoad = () => {
                                                      const key = `${selectedSubject}_${selectedClass}`;
                                                          const link = sheetLinks[key];

                                                              if (link) {
                                                                    const embedLink = link.replace("/edit", "/edit?usp=drivesdk");
                                                                          setSheetUrl(embedLink);
                                                                              } else {
                                                                                    alert("No Google Sheet found for this selection.");
                                                                                        }
                                                                                          };

                                                                                            const handleEdit = () => {
                                                                                                const key = `${selectedSubject}_${selectedClass}`;
                                                                                                    const link = sheetLinks[key];
                                                                                                        if (link) {
                                                                                                              const editLink = link.replace("/edit", "/edit?pli=1&authuser=0");
                                                                                                                    window.open(editLink, "_blank");
                                                                                                                        } else {
                                                                                                                              alert("No editable link found.");
                                                                                                                                  }
                                                                                                                                    };

                                                                                                                                      return (
                                                                                                                                          <>
                                                                                                                                          <Breadcrumb title="Assessment" />
                                                                                                                                         <Header />
                                                                                                                                         <br/>
                                                                                                                                         <a href="#/ins_guide">Download MEC App</a>
                                                                                                                                         <p>Please download Google Sheet from the playstore or apple store to be able to edit sheet.</p>
                                                                                                                                          <div style={{
                                                                                                                                                fontFamily: "Arial, sans-serif",
                                                                                                                                                      maxWidth: "900px",
                                                                                                                                                            margin: "2rem auto",
                                                                                                                                                                  padding: "2rem",
                                                                                                                                                                        border: "1px solid #e0e0e0",
                                                                                                                                                                              borderRadius: "12px",
                                                                                                                                                                                    boxShadow: "0 8px 24px rgba(0,0,0,0.1)"
                                                                                                                                                                                        }}>
                                                                                                                                                                                              <h1 style={{
                                                                                                                                                                                                      fontSize: "28px",
                                                                                                                                                                                                              textAlign: "center",
                                                                                                                                                                                                                      marginBottom: "2rem",
                                                                                                                                                                                                                              color: "#2c3e50"
                                                                                                                                                                                                                                    }}>
                                                                                                                                                                                                                                            Excel Assessment Sheet
                                                                                                                                                                                                                                                  </h1>

                                                                                                                                                                                                                                                        <div style={{ marginBottom: "1rem" }}>
                                                                                                                                                                                                                                                                <label style={{ display: "block", marginBottom: "6px", fontWeight: "bold" }}>Select Class:</label>
                                                                                                                                                                                                                                                                        <select
                                                                                                                                                                                                                                                                                  value={selectedClass}
                                                                                                                                                                                                                                                                                            onChange={(e) => setSelectedClass(e.target.value)}
                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                  padding: "10px",
                                                                                                                                                                                                                                                                                                                              width: "100%",
                                                                                                                                                                                                                                                                                                                                          borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                      border: "1px solid #ccc"
                                                                                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                  <option value="">-- Choose Class --</option>
                                                                                                                                                                                                                                                                                                                                                                                            {classes.map((cls) => (
                                                                                                                                                                                                                                                                                                                                                                                                        <option key={cls} value={cls}>{cls}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                          </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ marginBottom: "1rem" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                              <label style={{ display: "block", marginBottom: "6px", fontWeight: "bold" }}>Select Subject:</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      <select
                                                                                                                                                                                                                                                                                                                                                                                                                                                                value={selectedSubject}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setSelectedSubject(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "10px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            width: "100%",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "1px solid #ccc"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <option value="">-- Choose Subject --</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {subjects.map((subj) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option key={subj} value={subj}>{subj}</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div style={{ display: "flex", gap: "1rem", marginBottom: "1.5rem" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleLoad}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            padding: "12px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: "#3498db",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fontWeight: "bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Load Sheet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={handleEdit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                padding: "12px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: "#2ecc71",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        color: "#fff",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius: "6px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fontWeight: "bold"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Edit in Sheet
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {sheetUrl && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <iframe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          title="Google Sheet Preview"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    src={sheetUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              width="100%"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        height="600px"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              border: "1px solid #ccc",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          borderRadius: "6px"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default Assessment;