import React, { useState } from "react";
import Header from "../header";
import Breadcrumb from "../breadcrumb";

export default function LessonNoteTemp() {
  const [fileName, setFileName] = useState("lesson note template");

    return (
        <div>
            <Header />
            <Breadcrumb title="Digital Lesson Note" />

        <br /> 
                                                                                                                                        
                                                                                                                                          <br/>

                                                                                                                                                <div style={{ padding: "8px" }}>
                                                                                                                                                        <a
                                                                                                                                                                  href="https://docs.google.com/document/d/1ctMAqM1fzu0N1sEHPNFl_Aaim8unKRU-/edit?usp=drivesdk&ouid=116937019295659246684&rtpof=true&sd=true"
                                                                                                                                                                            download="lesson-note-template.docx"
                                                                                                                                                                                      style={{
                                                                                                                                                                                                  backgroundColor: "#28a745",
                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                          padding: "10px 20px",
                                                                                                                                                                                                                                      marginRight: "10px",
                                                                                                                                                                                                                                                  border: "none",
                                                                                                                                                                                                                                                              borderRadius: "5px",
                                                                                                                                                                                                                                                                          textDecoration: "none",
                                                                                                                                                                                                                                                                                      cursor: "pointer",
                                                                                                                                                                                                                                                                                                }}
                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                  Download Word Template
                                                                                                                                                                                                                                                                                                                          </a>


                                                                                                                                                                                                                                                                                                                                 <br/>
                                                                                                                                                                                                                                                                                                                                 <br/>
                                                                                                                                                                                                                                                                                                                                 <br/>
                                                                                                                                                                                                                                                                                                                                  <a
                                                                                                                                                                                                                                                                                                                                            href="https://drive.google.com/drive/folders/YOUR_FOLDER_ID"
                                                                                                                                                                                                                                                                                                                                                      target="_blank"
                                                                                                                                                                                                                                                                                                                                                                rel="noopener noreferrer"
                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                      display: "inline-block",
                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: "#007bff",
                                                                                                                                                                                                                                                                                                                                                                                                              color: "white",
                                                                                                                                                                                                                                                                                                                                                                                                                          padding: "10px 20px",
                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: "5px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                  textDecoration: "none",
                                                                                                                                                                                                                                                                                                                                                                                                                                                              cursor: "pointer",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Upload to Google Drive
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <br/>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }