import React, { useState, useRef, useCallback } from 'react';
import axios from 'axios';
import { useReactToPrint } from 'react-to-print';
import { Document, Header, Packer, Paragraph, TextRun } from 'docx';
import { saveAs } from 'file-saver';



function LessonNoteGenerator() {
  const [selectedClass, setSelectedClass] = useState('');
    const [selectedSubject, setSelectedSubject] = useState('');
      const [selectedTerm, setSelectedTerm] = useState('');
        const [selectedWeek, setSelectedWeek] = useState('');
          const [lessonData, setLessonData] = useState(null);
            const [loading, setLoading] = useState(false);
              const [error, setError] = useState('');

                const printRef = useRef(null);

                  const classes = [
                      'KG1', 'KG2', 'PRIMARY1', 'PRIMARY2', 'PRIMARY3', 'PRIMARY4', 'PRIMARY5', 'PRIMARY6',
                          'JHS1', 'JHS2', 'JHS3'
                            ];

                              const subjects = [
                                  'Mathematics', 'English Language', 'Science', 'Social Studies', 'ICT', 
                                      'Creative Arts', 'RME', 'Physical Education', 'Career Technology', 
                                          'French', 'Ghanaian Language'
                                            ];

                                              const terms = ['Term 1', 'Term 2', 'Term 3'];
                                                const weeks = Array.from({ length: 12 }, (_, i) => `Week ${i + 1}`);

                                                  const fetchLessonData = useCallback(async () => {
                                                      if (!selectedClass || !selectedSubject || !selectedTerm || !selectedWeek) {
                                                            setError('Please select class, subject, term, and week');
                                                                  return;
                                                                      }

                                                                          setLoading(true);
                                                                              setError('');
                                                                                  setLessonData(null);

                                                                                      try {
                                                                                            const params = new URLSearchParams({
                                                                                                    class: selectedClass,
                                                                                                            subject: selectedSubject,
                                                                                                                    term: selectedTerm,
                                                                                                                            week: selectedWeek
                                                                                                                                  });

                                                                                                                                        const response = await axios.get(
                                                                                                                                                `https://sheetdb.io/api/v1/8pxn3w6pupml1/search?${params.toString()}`
                                                                                                                                                      );

                                                                                                                                                            if (Array.isArray(response.data) && response.data.length > 0) {
                                                                                                                                                                    setLessonData(response.data[0]);
                                                                                                                                                                          } else {
                                                                                                                                                                                  setError('No lesson note found for the selected criteria');
                                                                                                                                                                                        }
                                                                                                                                                                                            } catch (err) {
                                                                                                                                                                                                  setError('Failed to fetch lesson data. Please check your connection.');
                                                                                                                                                                                                      } finally {
                                                                                                                                                                                                            setLoading(false);
                                                                                                                                                                                                                }
                                                                                                                                                                                                                  }, [selectedClass, selectedSubject, selectedTerm, selectedWeek]);

                                                                                                                                                                                                                    const handlePrint = useReactToPrint({
                                                                                                                                                                                                                        content: () => printRef.current,
                                                                                                                                                                                                                            documentTitle: `Lesson_Note_${selectedClass}_${selectedSubject}_${selectedTerm}_${selectedWeek}`,
                                                                                                                                                                                                                              });

                                                                                                                                                                                                                                const handleExportWord = async () => {
                                                                                                                                                                                                                                    if (!lessonData) return;

                                                                                                                                                                                                                                        const doc = new Document({
                                                                                                                                                                                                                                              sections: [
                                                                                                                                                                                                                                                      {
                                                                                                                                                                                                                                                                children: Object.entries(lessonData).map(([key, value]) =>
                                                                                                                                                                                                                                                                            new Paragraph({ children: [new TextRun({ text: `${key}: ${value}` })] })
                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                            const blob = await Packer.toBlob(doc);
                                                                                                                                                                                                                                                                                                                saveAs(blob, `Lesson_Note_${selectedClass}_${selectedSubject}_${selectedTerm}_${selectedWeek}.docx`);
                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                    const inputStyle = {
                                                                                                                                                                                                                                                                                                                        width: '100%',
                                                                                                                                                                                                                                                                                                                            padding: '12px',
                                                                                                                                                                                                                                                                                                                                marginBottom: '12px',
                                                                                                                                                                                                                                                                                                                                    borderRadius: '8px',
                                                                                                                                                                                                                                                                                                                                        border: '1px solid #ccc',
                                                                                                                                                                                                                                                                                                                                            fontSize: '14px'
                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                const buttonStyle = {
                                                                                                                                                                                                                                                                                                                                                    padding: '12px 24px',
                                                                                                                                                                                                                                                                                                                                                        margin: '8px',
                                                                                                                                                                                                                                                                                                                                                            borderRadius: '8px',
                                                                                                                                                                                                                                                                                                                                                                border: 'none',
                                                                                                                                                                                                                                                                                                                                                                    cursor: 'pointer',
                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#1e40af',
                                                                                                                                                                                                                                                                                                                                                                            color: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                fontWeight: '600'
                                                                                                                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                                                                                                                    const cardStyle = {
                                                                                                                                                                                                                                                                                                                                                                                        backgroundColor: '#fff',
                                                                                                                                                                                                                                                                                                                                                                                            borderRadius: '12px',
                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: '0 4px 6px rgba(0,0,0,0.1)',
                                                                                                                                                                                                                                                                                                                                                                                                    padding: '20px',
                                                                                                                                                                                                                                                                                                                                                                                                        marginBottom: '24px'
                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                                                                                                <>
                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                <div style={{ minHeight: '100vh', background: '#f1f5f9', padding: '24px', fontFamily: 'Arial, sans-serif' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ maxWidth: '900px', margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                              <h1 style={{ fontSize: '2rem', fontWeight: '700', color: '#1e40af', textAlign: 'center', marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                        GES Lesson Note Generator
                                                                                                                                                                                                                                                                                                                                                                                                                                                </h1>

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <select style={inputStyle} value={selectedClass} onChange={e => setSelectedClass(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <option value="">Select Class</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {classes.map(c => <option key={c} value={c}>{c}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <select style={inputStyle} value={selectedSubject} onChange={e => setSelectedSubject(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <option value="">Select Subject</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {subjects.map(s => <option key={s} value={s}>{s}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <select style={inputStyle} value={selectedTerm} onChange={e => setSelectedTerm(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <option value="">Select Term</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {terms.map(t => <option key={t} value={t}>{t}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <select style={inputStyle} value={selectedWeek} onChange={e => setSelectedWeek(e.target.value)}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <option value="">Select Week</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {weeks.map(w => <option key={w} value={w}>{w}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </select>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={buttonStyle} onClick={fetchLessonData}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {loading ? 'Loading...' : 'Generate Lesson Note'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {error && <div style={{ ...cardStyle, backgroundColor: '#fee2e2', color: '#b91c1c' }}>{error}</div>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {lessonData && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '12px', marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <button style={buttonStyle} onClick={handlePrint}>🖨️ Print / Save PDF</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button style={buttonStyle} onClick={handleExportWord}>📄 Export to Word</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div ref={printRef} style={cardStyle}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h2 style={{ color: '#1e40af' }}>Lesson Note Preview</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {Object.entries(lessonData).map(([key, value]) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={key} style={{ marginBottom: '10px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>{key}:</strong>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ ...inputStyle, minHeight: '60px' }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={value}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            setLessonData({ ...lessonData, [key]: e.target.value })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export default LessonNoteGenerator;