import React, { useState, useRef, useCallback } from 'react';
import axios from 'axios';
import { useReactToPrint } from 'react-to-print';
import { Document, Packer, Paragraph, TextRun } from 'docx';
import { saveAs } from 'file-saver';

const LessonNoteGenerator = ({ apiId = '8pxn3w6pupml1' }) => {
  const [selectedClass, setSelectedClass] = useState('');
    const [selectedSubject, setSelectedSubject] = useState('');
      const [selectedWeek, setSelectedWeek] = useState('');
        const [lessonData, setLessonData] = useState(null);
          const [loading, setLoading] = useState(false);
            const [error, setError] = useState('');
              const [feedback, setFeedback] = useState('');
                const [submittingFeedback, setSubmittingFeedback] = useState(false);

                  const printRef = useRef();

                    const classes = ['JHS1', 'JHS2', 'JHS3', 'SHS1', 'SHS2', 'SHS3', 
                                       'PRIMARY1', 'PRIMARY2', 'PRIMARY3', 'PRIMARY4', 'PRIMARY5', 'PRIMARY6'];

                                         const subjects = [
                                             'ICT', 'Mathematics', 'English Language', 'Science',
                                                 'Social Studies', 'French', 'Ghanaian Language', 'RME',
                                                     'Creative Arts', 'Physical Education', 'Career Technology'
                                                       ];

                                                         const weeks = Array.from({ length: 20 }, (_, i) => `Week ${i + 1}`);

                                                           const colors = {
                                                               primary: '#1e40af',
                                                                   secondary: '#059669',
                                                                       gray100: '#f1f5f9',
                                                                           gray300: '#cbd5e1',
                                                                               gray700: '#334155',
                                                                                   white: '#ffffff',
                                                                                       red500: '#ef4444',
                                                                                         };

                                                                                           // Fetch Lesson Data
                                                                                             const fetchLessonData = useCallback(async () => {
                                                                                                 if (!selectedClass || !selectedSubject) {
                                                                                                       setError('Please select both class and subject');
                                                                                                             return;
                                                                                                                 }

                                                                                                                     setLoading(true);
                                                                                                                         setError('');
                                                                                                                             setLessonData(null);

                                                                                                                                 try {
                                                                                                                                       const params = new URLSearchParams({
                                                                                                                                               class: selectedClass,
                                                                                                                                                       subject: selectedSubject,
                                                                                                                                                               ...(selectedWeek && { week: selectedWeek })
                                                                                                                                                                     });

                                                                                                                                                                           const response = await axios.get(
                                                                                                                                                                                   `https://sheetdb.io/api/v1/${apiId}/search?${params.toString()}`
                                                                                                                                                                                         );

                                                                                                                                                                                               if (response.data && response.data.length > 0) {
                                                                                                                                                                                                       setLessonData(response.data[0]);
                                                                                                                                                                                                             } else {
                                                                                                                                                                                                                     setError('No lesson note found for the selected criteria');
                                                                                                                                                                                                                           }
                                                                                                                                                                                                                               } catch (err) {
                                                                                                                                                                                                                                     setError('Failed to fetch lesson data. Please check your connection and try again.');
                                                                                                                                                                                                                                         } finally {
                                                                                                                                                                                                                                               setLoading(false);
                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                     }, [selectedClass, selectedSubject, selectedWeek, apiId]);

                                                                                                                                                                                                                                                       // Print
                                                                                                                                                                                                                                                         const handlePrint = useReactToPrint({
                                                                                                                                                                                                                                                             content: () => printRef.current,
                                                                                                                                                                                                                                                                 documentTitle: `Lesson_Note_${selectedClass}_${selectedSubject}_${selectedWeek || 'All'}`,
                                                                                                                                                                                                                                                                   });

                                                                                                                                                                                                                                                                     // Export to Word
                                                                                                                                                                                                                                                                       const handleExportWord = async () => {
                                                                                                                                                                                                                                                                           if (!lessonData) return;

                                                                                                                                                                                                                                                                               const doc = new Document({
                                                                                                                                                                                                                                                                                     sections: [
                                                                                                                                                                                                                                                                                             {
                                                                                                                                                                                                                                                                                                       children: [
                                                                                                                                                                                                                                                                                                                   new Paragraph({ children: [new TextRun({ text: "GHANA EDUCATION SERVICE", bold: true, size: 32 })] }),
                                                                                                                                                                                                                                                                                                                               new Paragraph({ children: [new TextRun({ text: "LESSON NOTE", bold: true, size: 28 })] }),
                                                                                                                                                                                                                                                                                                                                           new Paragraph({ text: `Class: ${lessonData.class}` }),
                                                                                                                                                                                                                                                                                                                                                       new Paragraph({ text: `Subject: ${lessonData.subject}` }),
                                                                                                                                                                                                                                                                                                                                                                   new Paragraph({ text: `Week: ${lessonData.week}` }),
                                                                                                                                                                                                                                                                                                                                                                               new Paragraph({ text: `Strand: ${lessonData.strand}` }),
                                                                                                                                                                                                                                                                                                                                                                                           new Paragraph({ text: `Sub-Strand: ${lessonData.sub_strand}` }),
                                                                                                                                                                                                                                                                                                                                                                                                       new Paragraph({ text: `Indicators: ${lessonData.indicators}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                   new Paragraph({ text: `Lesson Objectives: ${lessonData.lesson_objectives}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                               new Paragraph({ text: `Learning Materials: ${lessonData.learning_materials}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                                           new Paragraph({ text: `Core Competencies: ${lessonData.core_competencies}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                       new Paragraph({ text: `Introduction: ${lessonData.introduction}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                   new Paragraph({ text: `Activities: ${lessonData.activities}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               new Paragraph({ text: `Conclusion: ${lessonData.conclusion}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           new Paragraph({ text: `Assessment Questions: ${lessonData.assessment_questions}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       new Paragraph({ text: `Remarks: ${lessonData.remarks}` }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const blob = await Packer.toBlob(doc);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           saveAs(blob, `Lesson_Note_${lessonData.class}_${lessonData.subject}_${lessonData.week}.docx`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div style={{ minHeight: '100vh', background: colors.gray100, padding: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div style={{ textAlign: 'center', marginBottom: '32px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <h1 style={{ fontSize: '2.5rem', fontWeight: '700', color: colors.primary }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       GES Lesson Note Generator
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </h1>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {/* Selection Controls */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div style={{ backgroundColor: colors.white, borderRadius: '12px', padding: '24px', marginBottom: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <select value={selectedClass} onChange={(e) => setSelectedClass(e.target.value)} style={{ width: '100%', marginBottom: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <option value="">Select Class</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {classes.map((cls) => <option key={cls} value={cls}>{cls}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <select value={selectedSubject} onChange={(e) => setSelectedSubject(e.target.value)} style={{ width: '100%', marginBottom: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <option value="">Select Subject</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {subjects.map((subj) => <option key={subj} value={subj}>{subj}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <select value={selectedWeek} onChange={(e) => setSelectedWeek(e.target.value)} style={{ width: '100%', marginBottom: '16px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <option value="">Select Week</option>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {weeks.map((week) => <option key={week} value={week}>{week}</option>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </select>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <button onClick={fetchLessonData} disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   {loading ? 'Loading...' : 'Generate Lesson Note'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {error && <div style={{ color: colors.red500, marginBottom: '20px' }}>{error}</div>}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     {/* Lesson Note Display */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {lessonData && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div style={{ display: 'flex', gap: '12px', marginBottom: '20px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <button onClick={handlePrint}>🖨️ Print / Save PDF</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <button onClick={handleExportWord}>📄 Export to Word</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div ref={printRef} style={{ backgroundColor: colors.white, borderRadius: '12px', padding: '24px' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <h2 style={{ color: colors.primary }}>Lesson Note Preview</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p><strong>Class:</strong> {lessonData.class}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p><strong>Subject:</strong> {lessonData.subject}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <p><strong>Week:</strong> {lessonData.week}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <p><strong>Strand:</strong> {lessonData.strand}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <p><strong>Sub-Strand:</strong> {lessonData.sub_strand}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <p><strong>Indicators:</strong> {lessonData.indicators}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <p><strong>Lesson Objectives:</strong> {lessonData.lesson_objectives}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <p><strong>Learning Materials:</strong> {lessonData.learning_materials}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <p><strong>Core Competencies:</strong> {lessonData.core_competencies}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p><strong>Introduction:</strong> {lessonData.introduction}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <p><strong>Activities:</strong> {lessonData.activities}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <p><strong>Conclusion:</strong> {lessonData.conclusion}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <p><strong>Assessment Questions:</strong> {lessonData.assessment_questions}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <p><strong>Remarks:</strong> {lessonData.remarks}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   export default LessonNoteGenerator;