import React, { useEffect, useState } from "react";
import StudentPortal from "../portal/student_portal";
import ParentPortal from "../portal/parent_portal";
import TeachersPortal from "../portal/teachers_portal";
import Daycarestaffportal from "../portal/daycarestaff";
import bcrypt from "bcryptjs";

const path = process.env.REACT_APP_ACCOUNT_API;

export default function SignLog() {
  const [portalId, setPortalId] = useState("");
    const [portalKey, setPortalKey] = useState("");
      const [rememberMe, setRememberMe] = useState(false);
        const [loginError, setLoginError] = useState("");
          const [loading, setLoading] = useState(false);
            const [portalType, setPortalType] = useState("");

              useEffect(() => {
                  // Load saved credentials if "Remember Me" was checked
                      setPortalId(localStorage.getItem("portalid") || "");
                          setPortalKey(localStorage.getItem("portalkey") || "");
                              setRememberMe(JSON.parse(localStorage.getItem("portalcheck")) || false);
                                }, []);

                                  const handleLogin = async (e) => {
                                      e.preventDefault();
                                          setLoading(true);
                                              setLoginError("");

                                                  try {
                                                        const endpoints = [
                                                                `${path}/studentaccount`,
                                                                        `${path}/staffaccount`,
                                                                                `${path}/parentaccount`,
                                                                                      ];

                                                                                            const responses = await Promise.all(endpoints.map((url) => fetch(url)));
                                                                                                  const data = await Promise.all(responses.map((res) => res.json()));

                                                                                                        // Flattening all user data into one array
                                                                                                              const allUsers = data.flat();

                                                                                                                    const user = allUsers.find((user) => user.id === portalId);

                                                                                                                          if (!user) {
                                                                                                                                  throw new Error("Invalid User ID or Password");
                                                                                                                                        }

                                                                                                                                              const passwordCheck = bcrypt.compareSync(portalKey, user.passcode);

                                                                                                                                                    if (!passwordCheck || user.status !== "enrolled") {
                                                                                                                                                            throw new Error("Invalid User ID or Password");
                                                                                                                                                                  }

                                                                                                                                                                        // Save credentials if "Remember Me" is checked
                                                                                                                                                                              if (rememberMe) {
                                                                                                                                                                                      localStorage.setItem("portalid", portalId);
                                                                                                                                                                                              localStorage.setItem("portalkey", portalKey);
                                                                                                                                                                                                      localStorage.setItem("portalcheck", JSON.stringify(rememberMe));
                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                    localStorage.removeItem("portalid");
                                                                                                                                                                                                                            localStorage.removeItem("portalkey");
                                                                                                                                                                                                                                    localStorage.removeItem("portalcheck");
                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                // Update last seen time
                                                                                                                                                                                                                                                      const now = new Date();
                                                                                                                                                                                                                                                            await fetch(`${path}/${user.role === "student" ? "studentaccount" : "staffaccount"}/${user.id}`, {
                                                                                                                                                                                                                                                                    method: "PATCH",
                                                                                                                                                                                                                                                                            body: JSON.stringify({ lastseen: now.toLocaleString() }),
                                                                                                                                                                                                                                                                                    headers: { "Content-Type": "application/json" },
                                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                                                setPortalType(user.role);
                                                                                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                                                                                          setLoginError(error.message);
                                                                                                                                                                                                                                                                                                              } finally {
                                                                                                                                                                                                                                                                                                                    setLoading(false);
                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                            return (
                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                      <section className="containerS">
                                                                                                                                                                                                                                                                                                                                              <div className="formpage login">
                                                                                                                                                                                                                                                                                                                                                        <a onClick={() => window.history.back()} style={{ fontSize: "30px", cursor: "pointer" }}>
                                                                                                                                                                                                                                                                                                                                                                    &times;
                                                                                                                                                                                                                                                                                                                                                                              </a>

                                                                                                                                                                                                                                                                                                                                                                                        <div className="form-content">
                                                                                                                                                                                                                                                                                                                                                                                                    <header>Login</header>
                                                                                                                                                                                                                                                                                                                                                                                                                <form className="form" onSubmit={handleLogin}>
                                                                                                                                                                                                                                                                                                                                                                                                                              {loginError && <p style={{ color: "red" }}>{loginError}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="field input-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="User_Id"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  value={portalId}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onChange={(e) => setPortalId(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="field input-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={portalKey}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={(e) => setPortalKey(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a onClick={() => (window.location.href = "#/fgps")}>Forgot password</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="form-link">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="checkbox"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            checked={rememberMe}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChange={(e) => setRememberMe(e.target.checked)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <label>Remember me</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="form-link">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Don't have an account? <a href="#/account">Create one</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="field button-field">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button type="submit" disabled={loading}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {loading ? "Logging in..." : "Login"}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {portalType === "student" && <StudentPortal />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {portalType === "staff" && <TeachersPortal />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {portalType === "parent" && <ParentPortal />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {portalType === "daycarestaff" && <Daycarestaffportal />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }